services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile 
    working_dir: /app
    volumes:
      - .:/app  
      - /app/node_modules  
    ports:
      - "4200:4200" 
    environment:
      - CHOKIDAR_USEPOLLING=true  
    profiles:
      - dev  

  angular-prod:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:80"  
    profiles:
      - prod  
